---
sidebar: sidebar 
permalink: saved-search-capabilities.html 
keywords: flash, fabric, storage, interoperability, matrix, tool, imt, ONTAP SAN Host Simplified, storage, area, network, search, criteria, solution , explorer 
summary: Puede cargar diferentes soluciones o configuraciones utilizando el menú *Búsqueda guardada*, que le permite navegar a los resultados de búsqueda guardados anteriormente, los resultados de búsqueda recientes y las configuraciones guardadas. 
---
= Capacidades de búsqueda guardadas
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Puede cargar diferentes soluciones o configuraciones utilizando el menú *Búsqueda guardada*, que le permite navegar a los resultados de búsqueda guardados anteriormente, los resultados de búsqueda recientes y las configuraciones guardadas.

La pestaña *Criterios de búsqueda* contiene las búsquedas guardadas. En esta pestaña, puede compartir búsquedas o ver búsquedas que otros han compartido con usted. La pestaña *Configuración* contiene las configuraciones guardadas. En esta pestaña puede compartir configuraciones o ver configuraciones que otros han compartido con usted.

La pestaña *Búsqueda reciente* contiene los últimos 30 conjuntos de criterios de búsqueda, desde los más recientes hasta los más antiguos. También enumera el *Search Flow* que indica la página de origen, que puede ser *List and Find, Solution Explorer o Advanced Search*. Los criterios se guardan automáticamente. Esta página también muestra la *Fecha de Última Modificación* de una búsqueda guardada o reciente. Puede *Cargar* una búsqueda de la lista para ver los criterios o configuraciones respectivamente.
